spring:
  application:
    name: eureka-server

---
spring:
  profiles: server1
server:
  port: 8761

eureka:
#  server:
#    enable-self-preservation: false
  instance:
    hostname: server1
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://server2:8762/eureka/,http://server3:8763/eureka/
---
spring:
  profiles: server2
server:
  port: 8762
eureka:
  instance:
    hostname: server2
  client:
    serviceUrl:
      defaultZone: http://server3:8763/eureka/,http://server1:8761/eureka/

---
spring:
  profiles: server3
server:
  port: 8763
eureka:
  instance:
    hostname: server3
  client:
    serviceUrl:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/